---
apiVersion: v1
kind: Namespace
metadata:
  name: netpong-1

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netpong-service-account
  namespace: netpong-1

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netpong-cluster-role
  namespace: netpong-1
rules:
  - apiGroups:
        - ""
    resources:
      - pods
      - namespaces
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netpong-cluster-role-binding
subjects:
- namespace: netpong-1
  kind: ServiceAccount
  name: netpong-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netpong-cluster-role

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netpong-deployment
  namespace: netpong-1
spec:
  selector:
    matchLabels:
      app: netpong
  replicas: 2
  template:
    metadata:
      labels:
        app: netpong
    spec:
      serviceAccountName: netpong-service-account
      imagePullSecrets:
        - name: acr-netpong-pull
      containers:
      - name: netpong
        image: ltmarvin.azurecr.io/netpong:latest
        imagePullPolicy: Always
        command: ["/netpong"]
        args: ["--debug=true", "--namespace-prefix=netpong"]
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m